services:
  locust:
    build:
      context: .
    image: load-chaos-service-locust:latest
    ports:
      - "8089:8089"
    environment:
      LOCUST_SCENARIO: dataset_day
    command: >
      locust -f locust/locustfile.py
      --host=http://138.16.162.15:8000
      --headless
      --run-time 20m
