version: "3.9"

services:
  locust:
    build: .
    ports:
      - "8089:8089"
    environment:
      LOCUST_SCENARIO: dataset_day
      LOCUST_ACCOUNT_REFRESH_TTL: 60
      LOCUST_CREATE_PROB_NORMAL: 0.05
      LOCUST_CREATE_PROB_MIXED: 0.02
    command: >
      locust -f locustfile.py
      --host=http://138.16.162.15:8000
